export default {
"prolonged vaginal bleeding"    : false,
"back pain"                         : false,
"weight loss"                       : false,
"nausea"                            : false,
"pain during sexual intercourse"    : false,
"abdominal pain"                    : false,
"vaginal discharge"                 : false,
"vomiting"                          : false,
"abnormal bleeding"                 : false,
"lower abdominal pain"              : false,
"post menopausal bleeding"          : false,
"prolonged vaginal watery discharge": false,
"difficulty passing stool"          : false,
"fever"                             : false,
"cough"                             : false,
"difficulty micturation"            : false,
"chest pain"                        : false,
"lower back pain"                   : false,
"frequent micturation"              : false,
"waist pain"                        : false,
"pelvic pain"                       : false,
"lower limbs swelling"              : false,
"fatigue"                           : false,
"swelling"                          : false,
"yellowish vaginal discharge"       : false,
"foul smelling discharge"           : false,
"post coital bleeding"              : false,
"rectal bleeding"                   : false,
"constipation"                      : false,
"difficulty in breathing"           : false,
"occasional painful defecation"     : false,
"blood in urine"                    : false,
"headache"                          : false,
"palpitations"                      : false,
"vulva itching"                     : false,
"vaginal pain"                      : false,
"spot bleeding"                     : false,
"metromenorrhagia": false,
}